services:
  mongo:
    image: mongo:7.0
    container_name: events-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - .:/scripts

  api:
    build: .
    container_name: events-api-mongo
    restart: always
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/
      MONGO_DB_NAME: events_db
    ports:
      - "8001:8000"

volumes:
  mongo_data:
